checksumBehavior: update

enableGlobalCache: true

nodeLinker: pnp

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

packageExtensions:
  "@next/mdx@*":
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  vite-plugin-image-optimizer@*:
    dependencies:
      sharp: "*"
      svgo: "*"

pnpIgnorePatterns:
  - ./mobile-packages/**

yarnPath: .yarn/releases/yarn-4.7.0.cjs
