enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@next/mdx@*":
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"
  vite-plugin-image-optimizer@*:
    dependencies:
      sharp: "*"
      svgo: "*"

pnpIgnorePatterns:
  - ./mobile-packages/**

yarnPath: .yarn/releases/yarn-4.1.1.cjs

checksumBehavior: update
