name: Lib Publish

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/libPublish.yml
      - packages/lib-*/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Build
        run: |
          yarn install --immutable
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Publish "lib-sdk"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-sdk/

      - name: Publish "lib-sdk-react"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-sdk-react/

      - name: Publish "lib-sdk-react-dom"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-sdk-react-dom/

      - name: Publish "lib-sdk-react-native"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-sdk-react-native/

      - name: Publish "lib-sdk-expo"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-sdk-expo/

      - name: Publish "lib-cli"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: ./packages/lib-cli/
