name: Tests

on:
  push:
    paths:
      - packages/lib-*/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Build
        run: |
          yarn install --immutable
          yarn ${{ env.PROJECT_NAME }}:build

      - name: Run tests
        run: |
          yarn test
