name: Tests

on:
  push:
    paths:
      - .github/workflows/tests.yml
      - packages/lib-*/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - name: Run tests
        run: |
          yarn install --immutable
          yarn test
